apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  # credentials are base64 encoded to prevent issues with special characters and to "protect" it against "normal" people with no basic understanding of it
  # windows: [System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("text"))
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==